apiVersion: v1          # The core Kubernetes API group for basic primitives
kind: Namespace         # The type of resource being created
metadata:               # Metadata that identifies this specific object
  name: minishop-dev    # The unique name of your namespace
  labels:               # Key-value metadata used for filtering/selecting
    environment: dev
    app: minishop