apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: minishop-dev
type: Opaque # Standard key-value secret type
stringData:  # "stringData" lets you write plain text; Kubernetes base64-encodes it automatically on apply!
  POSTGRES_USER: "minishop_user"
  POSTGRES_PASSWORD: "supersecretpassword123"