apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: minishop-dev
spec:
  clusterIP: None # Makes this a Headless Service
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres