apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: minishop-dev
spec:
  serviceName: "postgres-service" # Links to our Headless Service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          
          # Inject DB credentials from Secret & ConfigMap
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config

          # Mount persistent disk + init script file
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        # Volume 1: Mounted from our ConfigMap containing init.sql
        - name: init-script
          configMap:
            name: postgres-init-script

  # Volume 2: Dynamic persistent storage auto-created per pod replica
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi