apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: minishop-dev
spec:
  type: ClusterIP # Default internal service type
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis