apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: minishop-dev
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest # Built from frontend/Dockerfile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          
          # Overwrite default Nginx config with our custom reverse-proxy ConfigMap
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config